import {NextResponse} from 'next/server';
import {getAdminContext} from '@/lib/admin-access';
const categories=new Set(['destination_guide','itinerary','food_drink','stay','cafe','activity','event_news','travel_advice','local_story','deal']);
const commercialTypes=new Set(['organic','affiliate','sponsored']);
const statuses=new Set(['draft','review','published','archived']);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const text=(value:unknown,limit:number)=>typeof value==='string'?value.trim().slice(0,limit):'';
const ids=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter(item=>typeof item==='string'&&UUID.test(item)))].slice(0,50):[];
export async function POST(request:Request){const{supabase,user,admin}=await getAdminContext();if(!user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!admin)return NextResponse.json({error:'ไม่มีสิทธิ์ Admin'},{status:403});const body=await request.json();const title=text(body.title,180),slug=text(body.slug,180),category=text(body.category,40),commercialType=text(body.commercialType,20),publicationStatus=text(body.publicationStatus,20);if(title.length<5||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)||!categories.has(category)||!commercialTypes.has(commercialType)||!statuses.has(publicationStatus))return NextResponse.json({error:'ข้อมูลบทความไม่ถูกต้อง'},{status:400});const bodyMarkdown=text(body.bodyMarkdown,100000);if(!bodyMarkdown)return NextResponse.json({error:'กรุณาใส่เนื้อหาบทความ'},{status:400});const sponsorName=text(body.sponsorName,120)||null,affiliateDisclosure=text(body.affiliateDisclosure,300)||null;if(commercialType==='sponsored'&&!sponsorName)return NextResponse.json({error:'Sponsored ต้องระบุชื่อ Sponsor'},{status:400});if(commercialType==='affiliate'&&!affiliateDisclosure)return NextResponse.json({error:'Affiliate ต้องมี Disclosure'},{status:400});const reading=body.readingMinutes?Number(body.readingMinutes):null;if(reading!==null&&(!Number.isInteger(reading)||reading<1||reading>180))return NextResponse.json({error:'เวลาอ่านไม่ถูกต้อง'},{status:400});const publishedAt=publicationStatus==='published'?new Date().toISOString():null;const{data,error}=await supabase.from('articles').insert({title,slug,excerpt:text(body.excerpt,500)||null,body_markdown:bodyMarkdown,category,destination_id:text(body.destinationId,80)||null,reading_minutes:reading,is_featured:body.featured==='on',commercial_type:commercialType,sponsor_name:sponsorName,affiliate_disclosure:affiliateDisclosure,seo_title:text(body.seoTitle,70)||null,seo_description:text(body.seoDescription,180)||null,publication_status:publicationStatus,published_at:publishedAt}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:500});const placeIds=ids(body.placeIds),eventIds=ids(body.eventIds);const relationError=(placeIds.length?(await supabase.from('article_places').insert(placeIds.map((placeId,index)=>({article_id:data.id,place_id:placeId,sort_order:index})))).error:null)||(eventIds.length?(await supabase.from('article_events').insert(eventIds.map((eventId,index)=>({article_id:data.id,event_id:eventId,sort_order:index})))).error:null);if(relationError){await supabase.from('articles').delete().eq('id',data.id);return NextResponse.json({error:relationError.message},{status:500})}return NextResponse.json({id:data.id},{status:201});}
