import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {destinations,mapArticle} from '@/lib/editorial';
import {mapPlace} from '@/lib/places';
import {EditorialCard} from '@/components/editorial/EditorialCard';
import {PlaceCard} from '@/components/place/PlaceCard';
import styles from './destination.module.css';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const destination=destinations.find(item=>item.slug===slug);return destination?{title:destination.name,description:`คู่มือและไอเดียทริป${destination.name}จาก GepPao`}:{};}
export default async function DestinationPage({params}:Props){const{slug}=await params;const profile=destinations.find(item=>item.slug===slug);if(!profile)notFound();const supabase=await createClient();const{data:destination}=await supabase.from('destinations').select('id,name,slug,province').eq('slug',slug).maybeSingle();let articles:any[]=[];let places:any[]=[];if(destination?.id){const[articleResult,placeResult]=await Promise.all([supabase.from('articles').select('id,title,slug,excerpt,category,tags,cover_image_url,cover_alt_text,cover_approved_for_public,reading_minutes,is_featured,commercial_type,sponsor_name,published_at,destinations(name,slug),editorial_authors(display_name,slug)').eq('destination_id',destination.id).eq('publication_status','published').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).limit(6),supabase.from('places').select('*, place_images(id,image_url,alt_text,sort_order,is_cover), price_items(id,label,amount_min,amount_max,currency,price_unit,is_estimate)').eq('destination_id',destination.id).eq('publication_status','published').order('name').limit(6)]);articles=(articleResult.data??[]).map(mapArticle);places=(placeResult.data??[]).map(mapPlace);}return <main><header className={styles.hero} style={{'--accent':profile.accent} as React.CSSProperties}><div><Link href="/go" className={styles.back}>← เก็บเป๋า ไปไหน?</Link><span className={styles.province}>{profile.province}</span><h1>{profile.name}</h1><p>{profile.kicker}</p><div className={styles.actions}>{profile.plannerReady?<><Link href={`/planner?destination=${encodeURIComponent(profile.name)}`} className={styles.primary}>วางแผนทริป{profile.name}</Link><Link href="/search" className={styles.secondary}>ดูสถานที่ทั้งหมด</Link></>:<span className={styles.coming}>Content Hub กำลังเตรียมข้อมูล · ยังไม่เปิด Planner</span>}</div></div></header><section className={styles.section}><div className={styles.head}><div><span className="eyebrow">Stories & guides</span><h2>อ่านก่อนออกเดินทาง</h2></div></div>{articles.length?<div className={styles.storyGrid}>{articles.map(article=><EditorialCard key={article.id} article={article}/>)}</div>:<div className={styles.empty}><h3>กำลังเตรียมคู่มือ{profile.name}</h3><p>ยังไม่มีบทความที่ผ่าน Editorial Review สำหรับพื้นที่นี้ เราจะไม่สร้างข้อมูลเวลา ราคา หรือคำแนะนำสถานที่ขึ้นเอง</p></div>}</section>{places.length>0&&<section className={styles.section}><div className={styles.head}><div><span className="eyebrow">Published local data</span><h2>สถานที่ที่มีข้อมูลพร้อมใช้งาน</h2></div></div><div className={styles.placeGrid}>{places.map(place=><PlaceCard key={place.id} place={place}/>)}</div></section>}</main>}
