import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {categoryLabels} from '@/lib/editorial';
import styles from './story.module.css';
type Props={params:Promise<{slug:string}>};
async function load(slug:string){const supabase=await createClient();const{data}=await supabase.from('articles').select('*,destinations(name,slug),editorial_authors(display_name,slug)').eq('slug',slug).eq('publication_status','published').lte('published_at',new Date().toISOString()).maybeSingle();return data;}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const article=await load(slug);if(!article)return{};return{title:article.seo_title??article.title,description:article.seo_description??article.excerpt??undefined,alternates:article.canonical_url?{canonical:article.canonical_url}:undefined};}
export default async function StoryPage({params}:Props){const{slug}=await params;const article=await load(slug);if(!article)notFound();const paragraphs=String(article.body_markdown??'').split(/\n\s*\n/).filter(Boolean);return <main className={styles.page}><article><header><div className={styles.meta}><span>{categoryLabels[article.category]??article.category}</span>{article.destinations&&<span>{article.destinations.name}</span>}{article.reading_minutes&&<span>{article.reading_minutes} นาที</span>}</div>{article.commercial_type!=='organic'&&<div className={styles.disclosure}>{article.commercial_type==='sponsored'?`เนื้อหาสนับสนุน${article.sponsor_name?`โดย ${article.sponsor_name}`:''}`:article.affiliate_disclosure}</div>}<h1>{article.title}</h1>{article.excerpt&&<p className={styles.lead}>{article.excerpt}</p>}<p className={styles.byline}>{article.editorial_authors?.display_name&&`โดย ${article.editorial_authors.display_name}`}{article.published_at&&` · ${new Intl.DateTimeFormat('th-TH',{dateStyle:'long'}).format(new Date(article.published_at))}`}</p></header>{article.cover_approved_for_public&&article.cover_image_url&&<img className={styles.cover} src={article.cover_image_url} alt={article.cover_alt_text??''}/>}<div className={styles.content}>{paragraphs.map((paragraph:string,index:number)=><p key={index}>{paragraph}</p>)}</div></article></main>}
