'use client';
import {ChangeEvent,useState} from 'react';
export function EventImageManager({eventId,initialImages}:{eventId:string;initialImages:any[]}){
  const[images,setImages]=useState(initialImages),[msg,setMsg]=useState('');
  const[rightsHolder,setRightsHolder]=useState(''),[rightsConfirmed,setRightsConfirmed]=useState(false);
  async function upload(e:ChangeEvent<HTMLInputElement>){if(!rightsConfirmed||!rightsHolder.trim()){setMsg('กรุณาระบุเจ้าของสิทธิ์และยืนยันสิทธิ์ก่อนอัปโหลด');e.target.value='';return}for(const file of Array.from(e.target.files??[])){const f=new FormData();f.append('file',file);f.append('rightsHolder',rightsHolder.trim());f.append('rightsConfirmed','true');f.append('permissionEvidence','owner_dashboard_upload');const r=await fetch(`/api/business/events/${eventId}/images`,{method:'POST',body:f}),x=await r.json();if(r.ok)setImages(v=>[...v,x]);else setMsg(x.error)}e.target.value=''}
  async function remove(id:string){const r=await fetch(`/api/business/events/${eventId}/images`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageId:id})});if(r.ok)setImages(v=>v.filter(x=>x.id!==id))}
  return <section className="dashboard-card"><div className="section-head"><div><h2>รูป Event</h2><p className="muted">รูปใหม่จะรอตรวจสิทธิ์ก่อนแสดงสาธารณะ</p></div><label className="btn btn-primary">เพิ่มรูป<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div><div className="form-grid"><label>เจ้าของลิขสิทธิ์/ผู้ให้สิทธิ์<input value={rightsHolder} onChange={e=>setRightsHolder(e.target.value)}/></label><label><input type="checkbox" checked={rightsConfirmed} onChange={e=>setRightsConfirmed(e.target.checked)}/> ยืนยันสิทธิ์ในการส่งและให้ GepPao แสดงรูป</label></div><div className="place-image-grid">{images.map(i=><article key={i.id}><img src={i.image_url} alt="รูป Event"/><p className="muted">{i.approved_for_public?'อนุมัติแล้ว':'รอตรวจสิทธิ์'}</p><div className="image-actions"><button className="btn" onClick={()=>remove(i.id)}>ลบ</button></div></article>)}</div>{msg&&<p className="form-error">{msg}</p>}</section>
}
