'use client';
import {useMemo,useRef,useState} from 'react';
import {useLocale} from '@/components/i18n/LocaleProvider';
import {PlaceCard} from '@/components/place/PlaceCard';
import type {Place} from '@/types/place';
import styles from './HomeCategoryCarousel.module.css';
type Category='accommodation'|'restaurant'|'cafe'|'attraction'|'activity';
type Props={places:Place[]};
const labels:Record<Category,{th:string;en:string;icon:string}>={accommodation:{th:'ที่พัก',en:'Stays',icon:'⌂'},restaurant:{th:'ร้านอาหาร',en:'Restaurants',icon:'⌁'},cafe:{th:'คาเฟ่',en:'Cafés',icon:'☕'},attraction:{th:'ที่เที่ยว',en:'Attractions',icon:'⌖'},activity:{th:'กิจกรรม',en:'Activities',icon:'✦'}};
export function HomeCategoryCarousel({places}:Props){const{locale}=useLocale();const groups=useMemo(()=>Object.fromEntries((Object.keys(labels)as Category[]).map(key=>[key,places.filter(place=>place.type===key)])) as Record<Category,Place[]>,[places]);const available=(Object.keys(labels)as Category[]).filter(key=>groups[key].length>0);const[first]=available;const[active,setActive]=useState<Category>(first||'accommodation');const rail=useRef<HTMLDivElement>(null);if(!available.length)return null;const current=groups[active];const shift=(direction:-1|1)=>rail.current?.scrollBy({left:direction*rail.current.clientWidth*.84,behavior:'smooth'});return <section className={styles.section} aria-label={locale==='en'?'Explore place categories':'สำรวจตามประเภทสถานที่'}><div className={styles.head}><div><p className={styles.eyebrow}>{locale==='en'?'EXPLORE BY TYPE':'สำรวจตามประเภท'}</p><h2>{locale==='en'?'Find a stop for every kind of day':'เลือกจุดแวะให้ครบทุกจังหวะของทริป'}</h2><p>{locale==='en'?'Switch a category, then swipe through local places.':'เลือกประเภท แล้วเลื่อนดูสถานที่ในพื้นที่ได้ทันที'}</p></div><div className={styles.controls}><button type="button" onClick={()=>shift(-1)} aria-label={locale==='en'?'Previous places':'ดูรายการก่อนหน้า'}>←</button><button type="button" onClick={()=>shift(1)} aria-label={locale==='en'?'Next places':'ดูรายการถัดไป'}>→</button></div></div><div className={styles.tabs} role="tablist" aria-label={locale==='en'?'Place category':'ประเภทสถานที่'}>{available.map(category=><button key={category} role="tab" type="button" aria-selected={active===category} className={active===category?styles.activeTab:''} onClick={()=>{setActive(category);requestAnimationFrame(()=>rail.current?.scrollTo({left:0,behavior:'auto'}))}}><span>{labels[category].icon}</span>{locale==='en'?labels[category].en:labels[category].th}<small>{groups[category].length}</small></button>)}</div><div className={styles.rail} ref={rail} role="tabpanel">{current.map(place=><div className={styles.slide} key={place.id}><PlaceCard place={place}/></div>)}</div></section>}
