'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Brand} from '@/components/brand/Brand';
import {Logo} from '@/components/brand/Logo';
import {UserNav} from '@/components/auth/UserNav';
import {LanguageToggle} from '@/components/i18n/LanguageToggle';
import {useLocale} from '@/components/i18n/LocaleProvider';
import styles from './SiteChrome.module.css';
type Props={children:React.ReactNode;name:string;email:string|null;isAdmin:boolean};
export function SiteChrome({children,name,email,isAdmin}:Props){const{locale}=useLocale();const pathname=usePathname();const en=locale==='en';const nav=[['/','Home','หน้าหลัก'],['/go','Destinations','ไปไหนดี'],['/stories','Stories','เรื่องน่าอ่าน'],['/search','Explore','ค้นหาสถานที่'],['/planner','Plan trip','วางแผนทริป']];const mobile=[['/','Home','หน้าหลัก','⌂'],['/go','Go','ไปไหนดี','◇'],['/search','Explore','ค้นหา','⌕'],['/planner','Plan','วางแผน','✦'],['/trips','Trips','ทริป','♡']];const active=(href:string)=>href==='/'?pathname==='/':pathname.startsWith(href);return <div className={styles.shell}><a className="skipLink" href="#main-content">{en?'Skip to content':'ข้ามไปเนื้อหาหลัก'}</a><header className={styles.header}><div className={styles.inner}><Link href="/" className={styles.brandLink} aria-label="GepPao home"><Brand/></Link><nav className={styles.desktopNav} aria-label="Primary navigation">{nav.map(([href,enLabel,thLabel])=><Link key={href} href={href} className={`${styles.navLink} ${active(href)?styles.active:''}`}>{en?enLabel:thLabel}</Link>)}</nav><div className={styles.actions}><LanguageToggle/><UserNav name={name} email={email} isAdmin={isAdmin}/></div></div></header><div id="main-content" tabIndex={-1}>{children}</div><footer className={styles.footer}><div className={styles.footerInner}><div className={styles.footerGrid}><div><h4><Logo size={52} variant="light"/></h4><p>{en?'Travel stories with a useful next step.':'เรื่องเที่ยวที่ไม่ได้จบแค่แรงบันดาลใจ'}</p><p>{en?'Discover destinations, understand local context, and turn ideas into a practical trip.':'อ่านเรื่อง เลือกจุดหมาย และเปลี่ยนไอเดียให้เป็นทริปที่ใช้ได้จริง'}</p></div><div><h4>{en?'Discover':'ค้นพบ'}</h4><p><Link href="/stories">{en?'Stories':'เรื่องน่าอ่าน'}</Link></p><p><Link href="/go">{en?'Destinations':'เก็บเป๋า ไปไหน?'}</Link></p><p><Link href="/events">{en?'Events':'อีเวนต์'}</Link></p></div><div><h4>{en?'Plan':'วางแผน'}</h4><p><Link href="/search">{en?'Explore places':'ค้นหาสถานที่'}</Link></p><p><Link href="/planner">Trip Planner</Link></p><p><Link href="/trips">{en?'Saved trips':'ทริปของฉัน'}</Link></p></div><div><h4>{en?'Partners & information':'พาร์ตเนอร์และข้อมูล'}</h4><p><Link href="/host">{en?'Manage your place':'จัดการข้อมูลธุรกิจ'}</Link></p><p><Link href="/contact">{en?'Contact us':'ติดต่อเรา'}</Link></p><p><Link href="/privacy">{en?'Privacy':'ความเป็นส่วนตัว'}</Link> · <Link href="/terms">{en?'Terms':'ข้อกำหนด'}</Link></p></div></div><div className={styles.footerBottom}>GepPao · {en?'Stories → destinations → practical trips':'เรื่องเที่ยว → จุดหมาย → ทริปที่ไปได้จริง'}</div></div></footer><nav className={styles.mobileNav} aria-label="Mobile navigation">{mobile.map(([href,enLabel,thLabel,icon])=><Link key={href} href={href} className={`${styles.mobileLink} ${active(href)?styles.mobileActive:''}`}><span className={styles.mobileIcon}>{icon}</span>{en?enLabel:thLabel}</Link>)}</nav></div>}
