'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Brand} from '@/components/brand/Brand';
import {UserNav} from '@/components/auth/UserNav';
import {LanguageToggle} from '@/components/i18n/LanguageToggle';
import {useLocale} from '@/components/i18n/LocaleProvider';
import styles from './SiteChrome.module.css';
type Props={children:React.ReactNode;name:string;email:string|null;isAdmin:boolean};
export function SiteChrome({children,name,email,isAdmin}:Props){const{locale}=useLocale();const pathname=usePathname();const en=locale==='en';const nav=[['/','Discover','หน้าหลัก','⌂'],['/search','Explore','สำรวจ','⌕'],['/planner','Plan trip','วางแผน','✦'],['/trips','Saved trips','ทริปของฉัน','♡']];return <div className={styles.shell}><a className="skipLink" href="#main-content">{en?'Skip to content':'ข้ามไปเนื้อหาหลัก'}</a><header className={styles.header}><div className={styles.inner}><Link href="/" className={styles.brandLink} aria-label="GepPao home"><Brand/></Link><nav className={styles.desktopNav} aria-label="Primary navigation">{nav.map(([href,enLabel,thLabel])=><Link key={href} href={href} className={`${styles.navLink} ${(href==='/'?pathname==='/':pathname.startsWith(href))?styles.active:''}`}>{en?enLabel:thLabel}</Link>)}</nav><div className={styles.actions}><LanguageToggle/><UserNav name={name} email={email} isAdmin={isAdmin}/></div></div></header><div id="main-content" tabIndex={-1}>{children}</div><footer className={styles.footer}><div className={styles.footerInner}><div className={styles.footerGrid}><div><h4>GepPao</h4><p>{en?'A thoughtful local trip planner for Khao Yai and Pak Chong.':'แพลตฟอร์มวางแผนทริปเขาใหญ่และปากช่องอย่างตั้งใจ'}</p><p>{en?'Real local context, clear data confidence, and trips that feel easy to make.':'ข้อมูลท้องถิ่นที่ชัดเจน ความน่าเชื่อถือที่มองเห็นได้ และทริปที่วางแผนง่าย'}</p></div><div><h4>{en?'Explore':'สำรวจ'}</h4><p><Link href="/search">{en?'All places':'ทุกสถานที่'}</Link></p><p><Link href="/events">Events</Link></p><p><Link href="/planner">Trip Planner</Link></p></div><div><h4>{en?'For partners':'สำหรับพาร์ตเนอร์'}</h4><p><Link href="/host">{en?'Manage your place':'จัดการข้อมูลธุรกิจ'}</Link></p><p><Link href="/business/events">{en?'Manage events':'จัดการ Events'}</Link></p></div></div><div className={styles.footerBottom}>GepPao · {en?'Pak Chong — Khao Yai':'ปากช่อง — เขาใหญ่'}</div></div></footer><nav className={styles.mobileNav} aria-label="Mobile navigation">{nav.map(([href,enLabel,thLabel,icon])=><Link key={href} href={href} className={`${styles.mobileLink} ${(href==='/'?pathname==='/':pathname.startsWith(href))?styles.mobileActive:''}`}><span className={styles.mobileIcon}>{icon}</span>{en?enLabel:thLabel}</Link>)}</nav></div>}
