import type {DestinationCard,EditorialArticle} from '@/types/editorial';
export const destinations:DestinationCard[]=[
 {name:'เขาใหญ่',slug:'pak-chong-khao-yai',province:'นครราชสีมา',kicker:'ธรรมชาติ · คาเฟ่ · ครอบครัว',summary:'ฐานข้อมูลและ Planner พร้อมให้เริ่มจัดทริป',plannerReady:true,accent:'#17472d',imageSrc:'https://upload.wikimedia.org/wikipedia/commons/c/c3/Khao_Yai%2C_Thailand%2C_Tropical_grasslands.jpg',imageAlt:'ทุ่งหญ้าเขตร้อนในอุทยานแห่งชาติเขาใหญ่',imageCredit:'Vyacheslav Argenberg',imageSource:'https://commons.wikimedia.org/wiki/File:Khao_Yai,_Thailand,_Tropical_grasslands.jpg',imageLicense:'CC BY 4.0',imageLicenseUrl:'https://creativecommons.org/licenses/by/4.0'},
 {name:'พัทยา',slug:'pattaya',province:'ชลบุรี',kicker:'ทะเล · เมือง · กิจกรรม',summary:'กำลังเตรียมคู่มือและข้อมูลท้องถิ่น',plannerReady:false,accent:'#255f78',imageSrc:'https://upload.wikimedia.org/wikipedia/commons/e/e9/Pattaya_Bay%2C_Pattaya_Beach%2C_Thailand.jpg',imageAlt:'อ่าวพัทยาและชายหาดพัทยา',imageCredit:'Vyacheslav Argenberg',imageSource:'https://commons.wikimedia.org/wiki/File:Pattaya_Bay,_Pattaya_Beach,_Thailand.jpg',imageLicense:'CC BY 4.0',imageLicenseUrl:'https://creativecommons.org/licenses/by/4.0'},
 {name:'กาญจนบุรี',slug:'kanchanaburi',province:'กาญจนบุรี',kicker:'ธรรมชาติ · ประวัติศาสตร์ · Road trip',summary:'กำลังเตรียมคู่มือและข้อมูลท้องถิ่น',plannerReady:false,accent:'#80633f',imageSrc:'https://upload.wikimedia.org/wikipedia/commons/6/65/Kanchanaburi%2C_Kwai_River_and_River_Kwai_bridge%2C_Thailand.jpg',imageAlt:'แม่น้ำแควและสะพานข้ามแม่น้ำแคว จังหวัดกาญจนบุรี',imageCredit:'Vyacheslav Argenberg',imageSource:'https://commons.wikimedia.org/wiki/File:Kanchanaburi,_Kwai_River_and_River_Kwai_bridge,_Thailand.jpg',imageLicense:'CC BY 4.0',imageLicenseUrl:'https://creativecommons.org/licenses/by/4.0'},
 {name:'นครนายก',slug:'nakhon-nayok',province:'นครนายก',kicker:'น้ำตก · กิจกรรม · เที่ยววันเดียว',summary:'กำลังเตรียมคู่มือและข้อมูลท้องถิ่น',plannerReady:false,accent:'#516b3f',imageSrc:'https://upload.wikimedia.org/wikipedia/commons/b/b3/Khun_Dan_Prakarn_Chon_dam%2C_up_water_side.JPG',imageAlt:'อ่างเก็บน้ำเหนือเขื่อนขุนด่านปราการชล จังหวัดนครนายก',imageCredit:'Chatchawan',imageSource:'https://commons.wikimedia.org/wiki/File:Khun_Dan_Prakarn_Chon_dam,_up_water_side.JPG',imageLicense:'CC BY-SA 3.0',imageLicenseUrl:'https://creativecommons.org/licenses/by-sa/3.0'}
];
export const categoryLabels:Record<string,string>={destination_guide:'คู่มือจุดหมาย',itinerary:'แผนเที่ยว',food_drink:'กินและดื่ม',stay:'ที่พัก',cafe:'คาเฟ่',activity:'กิจกรรม',event_news:'อีเวนต์และข่าว',travel_advice:'คำแนะนำเดินทาง',local_story:'เรื่องเล่าท้องถิ่น',deal:'ดีล'};
export function mapArticle(row:any):EditorialArticle{return{id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt??null,category:row.category,tags:Array.isArray(row.tags)?row.tags:[],coverImageUrl:row.cover_approved_for_public?row.cover_image_url:null,coverAltText:row.cover_alt_text??null,readingMinutes:row.reading_minutes??null,featured:Boolean(row.is_featured),commercialType:row.commercial_type??'organic',sponsorName:row.sponsor_name??null,publishedAt:row.published_at??null,destination:row.destinations?{name:row.destinations.name,slug:row.destinations.slug}:null,author:row.editorial_authors?{displayName:row.editorial_authors.display_name,slug:row.editorial_authors.slug}:null};}
