import {NextResponse} from 'next/server';
import {getAdminContext} from '@/lib/admin-access';
const BUCKET='place-images',MAX=8*1024*1024,TYPES=new Set(['image/jpeg','image/png','image/webp']),BASES=new Set(['owner','licensed','public_domain','geppao_owned']);
const clean=(v:FormDataEntryValue|null,max:number)=>typeof v==='string'?v.trim().slice(0,max):'';
async function context(id:string){const c=await getAdminContext();if(!c.user||!c.admin)return {...c,place:null};const{data:place}=await c.supabase.from('places').select('id,business_id,place_images(id,image_url,sort_order,is_cover,alt_text,rights_holder,rights_basis,permission_evidence,permission_date,approved_for_public,takedown_status)').eq('id',id).is('business_id',null).maybeSingle();return {...c,place};}
function pathFromUrl(url:string){const marker=`/storage/v1/object/public/${BUCKET}/`,i=url.indexOf(marker);return i<0?null:decodeURIComponent(url.slice(i+marker.length));}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.admin)return NextResponse.json({error:'ไม่มีสิทธิ์ Admin'},{status:403});if(!c.place)return NextResponse.json({error:'ไม่พบ Place ที่ดูแลได้'},{status:404});
  const images=c.place.place_images??[];if(images.length>=12)return NextResponse.json({error:'Place หนึ่งแห่งใส่รูปได้สูงสุด 12 รูป'},{status:400});
  const form=await request.formData(),file=form.get('file'),rightsHolder=clean(form.get('rightsHolder'),200),rightsBasis=clean(form.get('rightsBasis'),30),permissionEvidence=clean(form.get('permissionEvidence'),500);
  if(form.get('rightsConfirmed')!=='true'||!rightsHolder||!BASES.has(rightsBasis)||!permissionEvidence)return NextResponse.json({error:'ต้องระบุเจ้าของสิทธิ์ ฐานสิทธิ์ และหลักฐานก่อนอัปโหลด'},{status:400});
  if(!(file instanceof File)||!TYPES.has(file.type)||file.size>MAX)return NextResponse.json({error:'ใช้ JPG, PNG หรือ WebP ขนาดไม่เกิน 8 MB'},{status:400});
  const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp',path=`admin/${id}/${crypto.randomUUID()}.${ext}`,{error:uploadError}=await c.supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type});if(uploadError)return NextResponse.json({error:uploadError.message},{status:500});
  const url=c.supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl,{data,error}=await c.supabase.from('place_images').insert({place_id:id,image_url:url,sort_order:images.length,is_cover:images.length===0,rights_holder:rightsHolder,rights_basis:rightsBasis,permission_evidence:permissionEvidence,permission_date:new Date().toISOString().slice(0,10),approved_for_public:false,takedown_status:'active'}).select('*').single();
  if(error){await c.supabase.storage.from(BUCKET).remove([path]);return NextResponse.json({error:error.message},{status:500})}return NextResponse.json(data,{status:201});
}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.admin)return NextResponse.json({error:'ไม่มีสิทธิ์ Admin'},{status:403});if(!c.place)return NextResponse.json({error:'ไม่พบ Place ที่ดูแลได้'},{status:404});
  const{imageId,action='cover'}=await request.json(),image=(c.place.place_images??[]).find((item:any)=>item.id===imageId);if(!image)return NextResponse.json({error:'ไม่พบรูปภาพ'},{status:404});
  if(action==='approve'){
    if(!pathFromUrl(image.image_url)||!image.rights_holder||!image.rights_basis||!image.permission_evidence||!image.permission_date)return NextResponse.json({error:'หลักฐานสิทธิ์ยังไม่ครบหรือไฟล์ไม่ได้อยู่ใน GepPao Storage'},{status:400});
    const{error}=await c.supabase.from('place_images').update({approved_for_public:true,approved_by:c.user.id,approved_at:new Date().toISOString(),takedown_status:'active'}).eq('id',imageId).eq('place_id',id);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({success:true,approved_for_public:true});
  }
  if(action==='revoke'){const{error}=await c.supabase.from('place_images').update({approved_for_public:false,approved_by:null,approved_at:null}).eq('id',imageId).eq('place_id',id);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({success:true,approved_for_public:false});}
  await c.supabase.from('place_images').update({is_cover:false}).eq('place_id',id);const{error}=await c.supabase.from('place_images').update({is_cover:true}).eq('id',imageId).eq('place_id',id);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({success:true});
}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.admin)return NextResponse.json({error:'ไม่มีสิทธิ์ Admin'},{status:403});if(!c.place)return NextResponse.json({error:'ไม่พบ Place ที่ดูแลได้'},{status:404});const{imageId}=await request.json(),image=(c.place.place_images??[]).find((item:any)=>item.id===imageId);if(!image)return NextResponse.json({error:'ไม่พบรูปภาพ'},{status:404});const path=pathFromUrl(image.image_url);if(!path||!path.startsWith(`admin/${id}/`))return NextResponse.json({error:'รูปภาพนี้ไม่ได้อยู่ในพื้นที่ curation'},{status:403});const{error}=await c.supabase.storage.from(BUCKET).remove([path]);if(error)return NextResponse.json({error:error.message},{status:500});await c.supabase.from('place_images').delete().eq('id',imageId).eq('place_id',id);if(image.is_cover){const next=(c.place.place_images??[]).find((item:any)=>item.id!==imageId);if(next)await c.supabase.from('place_images').update({is_cover:true}).eq('id',next.id)}return NextResponse.json({success:true});}
