'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {trackProductEvent} from '@/lib/analytics/client';
import {EventInterestButton} from '@/components/analytics/EventInterestButton';
import styles from './UnifiedSearchClient.module.css';
type Item={id:string;kind:'place'|'event';type:string;name:string;slug?:string;description:string;location:string;image:string|null;price:string;date:string};
const labels:Record<string,string>={all:'ทั้งหมด',accommodation:'ที่พัก',restaurant:'ร้านอาหาร',cafe:'คาเฟ่',attraction:'ที่เที่ยว',activity:'กิจกรรม',event:'อีเวนต์'};
export function UnifiedSearchClient({items}:{items:Item[]}){const[q,setQ]=useState('');const[type,setType]=useState('all');const lastTracked=useRef('');const results=useMemo(()=>items.filter(x=>(type==='all'||x.type===type)&&`${x.name} ${x.description} ${x.location}`.toLowerCase().includes(q.toLowerCase())),[items,q,type]);useEffect(()=>{if(!q.trim()&&type==='all')return;const key=`${q.trim().toLowerCase()}|${type}|${results.length}`;const timer=window.setTimeout(()=>{if(lastTracked.current===key)return;lastTracked.current=key;void trackProductEvent({eventName:'search',metadata:{queryLength:q.trim().length,placeType:type,resultCount:results.length}})},600);return()=>window.clearTimeout(timer)},[q,type,results.length]);return <><div className={styles.toolbar}><div className={styles.search}><label htmlFor="local-search">ค้นหา</label><div className={styles.searchInput}><span>⌕</span><input id="local-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="ชื่อสถานที่ บรรยากาศ หรือกิจกรรม"/></div></div><div className={styles.type}><label htmlFor="place-type">ประเภท</label><select id="place-type" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div></div><div className={styles.resultsHead}><p><strong>{results.length}</strong> ผลลัพธ์จาก Local Data ที่เผยแพร่แล้ว</p>{(q||type!=='all')&&<button onClick={()=>{setQ('');setType('all')}}>ล้างตัวกรอง</button>}</div><div className={styles.grid}>{results.map(x=><article className={styles.card} key={`${x.kind}-${x.id}`}><div className={styles.visual}>{x.image?<img src={x.image} alt={x.name}/>:<div className={styles.placeholder}>⌂</div>}<span className={styles.kind}>{labels[x.type]||x.type}</span></div><div className={styles.body}><h2>{x.name}</h2><p className={styles.location}>⌖ {x.location||'กำลังตรวจสอบที่อยู่'}</p>{x.description&&<p className={styles.description}>{x.description}</p>}<div className={styles.footer}><div>{x.price&&<span className={styles.price}>{x.price}</span>}{x.date&&<span className={styles.date}>{x.date}</span>}</div>{x.kind==='place'&&x.slug?<Link className="btn btn-sage" href={`/places/${x.slug}`}>ดูรายละเอียด</Link>:x.kind==='event'?<EventInterestButton eventId={x.id}/>:null}</div></div></article>)}</div>{!results.length&&<div className="setup-notice"><h3>ไม่พบข้อมูลที่ตรงเงื่อนไข</h3><p>ลองเปลี่ยนคำค้นหาหรือเลือกประเภทอื่นดูครับ</p></div>}</>}
