import {NextResponse} from 'next/server';
import {getBusinessContext} from '@/lib/business-access';
const BUCKET='place-images',MAX=8*1024*1024,TYPES=new Set(['image/jpeg','image/png','image/webp']);
const clean=(value:FormDataEntryValue|null,max:number)=>typeof value==='string'?value.trim().slice(0,max):'';
async function context(id:string){const c=await getBusinessContext();if(!c.user||!c.business)return {...c,place:null};const{data:place}=await c.supabase.from('places').select('id,business_id,place_images(id,image_url,sort_order,is_cover,alt_text,approved_for_public)').eq('id',id).eq('business_id',c.business.id).maybeSingle();return {...c,place};}
function pathFromUrl(url:string){const marker=`/storage/v1/object/public/${BUCKET}/`,i=url.indexOf(marker);return i<0?null:decodeURIComponent(url.slice(i+marker.length));}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.place||!c.business)return NextResponse.json({error:'ไม่พบ Place หรือไม่มีสิทธิ์'},{status:404});
  const images=c.place.place_images??[];if(images.length>=12)return NextResponse.json({error:'Place หนึ่งแห่งใส่รูปได้สูงสุด 12 รูป'},{status:400});
  const form=await request.formData(),file=form.get('file'),rightsHolder=clean(form.get('rightsHolder'),200),permissionEvidence=clean(form.get('permissionEvidence'),500);
  if(form.get('rightsConfirmed')!=='true'||!rightsHolder)return NextResponse.json({error:'ต้องระบุเจ้าของสิทธิ์และยืนยันสิทธิ์ก่อนอัปโหลด'},{status:400});
  if(!(file instanceof File)||!TYPES.has(file.type)||file.size>MAX)return NextResponse.json({error:'ใช้ JPG, PNG หรือ WebP ขนาดไม่เกิน 8 MB'},{status:400});
  const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp',path=`${c.business.id}/${id}/${crypto.randomUUID()}.${ext}`;
  const{error:uploadError}=await c.supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type});if(uploadError)return NextResponse.json({error:uploadError.message},{status:500});
  const url=c.supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;
  const{data,error}=await c.supabase.from('place_images').insert({place_id:id,image_url:url,sort_order:images.length,is_cover:images.length===0,rights_holder:rightsHolder,rights_basis:'owner',permission_evidence:permissionEvidence||'owner_dashboard_upload',permission_date:new Date().toISOString().slice(0,10),approved_for_public:false,takedown_status:'active'}).select('id,image_url,sort_order,is_cover,alt_text,approved_for_public').single();
  if(error){await c.supabase.storage.from(BUCKET).remove([path]);return NextResponse.json({error:error.message},{status:500})}return NextResponse.json(data,{status:201});
}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.place)return NextResponse.json({error:'ไม่พบ Place หรือไม่มีสิทธิ์'},{status:404});const{imageId}=await request.json();await c.supabase.from('place_images').update({is_cover:false}).eq('place_id',id);const{error}=await c.supabase.from('place_images').update({is_cover:true}).eq('id',imageId).eq('place_id',id);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({success:true});}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,c=await context(id);if(!c.user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!c.place||!c.business)return NextResponse.json({error:'ไม่พบ Place หรือไม่มีสิทธิ์'},{status:404});const{imageId}=await request.json(),image=(c.place.place_images??[]).find((x:any)=>x.id===imageId);if(!image)return NextResponse.json({error:'ไม่พบรูปภาพ'},{status:404});const path=pathFromUrl(image.image_url);if(!path||!path.startsWith(`${c.business.id}/${id}/`))return NextResponse.json({error:'เส้นทางรูปไม่ถูกต้อง'},{status:403});const{error}=await c.supabase.storage.from(BUCKET).remove([path]);if(error)return NextResponse.json({error:error.message},{status:500});await c.supabase.from('place_images').delete().eq('id',imageId).eq('place_id',id);if(image.is_cover){const next=(c.place.place_images??[]).find((x:any)=>x.id!==imageId);if(next)await c.supabase.from('place_images').update({is_cover:true}).eq('id',next.id)}return NextResponse.json({success:true});}
