import {NextResponse} from 'next/server';
import {getAdminContext} from '@/lib/admin-access';
const categories=new Set(['destination_guide','itinerary','food_drink','stay','cafe','activity','event_news','travel_advice','local_story','deal']);
const commercialTypes=new Set(['organic','affiliate','sponsored']);
const statuses=new Set(['draft','review','published','archived']);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const text=(value:unknown,limit:number)=>typeof value==='string'?value.trim().slice(0,limit):'';
const ids=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter(item=>typeof item==='string'&&UUID.test(item)))].slice(0,50):[];
async function syncRelations(supabase:any,articleId:string,table:'article_places'|'article_events',column:'place_id'|'event_id',nextIds:string[]){const{data,error}=await supabase.from(table).select(column).eq('article_id',articleId);if(error)return error;const current=new Set<string>((data??[]).map((row:any)=>String(row[column])));const add=nextIds.filter(value=>!current.has(value)),remove=[...current].filter(value=>!nextIds.includes(value));if(add.length){const{error:addError}=await supabase.from(table).insert(add.map(value=>({article_id:articleId,[column]:value,sort_order:nextIds.indexOf(value)})));if(addError)return addError}if(remove.length){const{error:removeError}=await supabase.from(table).delete().eq('article_id',articleId).in(column,remove);if(removeError)return removeError}for(let index=0;index<nextIds.length;index++){const{error:orderError}=await supabase.from(table).update({sort_order:index}).eq('article_id',articleId).eq(column,nextIds[index]);if(orderError)return orderError}return null}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase,user,admin}=await getAdminContext();if(!user)return NextResponse.json({error:'กรุณาเข้าสู่ระบบ'},{status:401});if(!admin)return NextResponse.json({error:'ไม่มีสิทธิ์ Admin'},{status:403});const body=await request.json();const title=text(body.title,180),slug=text(body.slug,180),category=text(body.category,40),commercialType=text(body.commercialType,20),publicationStatus=text(body.publicationStatus,20),bodyMarkdown=text(body.bodyMarkdown,100000);if(title.length<5||!bodyMarkdown||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)||!categories.has(category)||!commercialTypes.has(commercialType)||!statuses.has(publicationStatus))return NextResponse.json({error:'ข้อมูลบทความไม่ถูกต้อง'},{status:400});const sponsorName=text(body.sponsorName,120)||null,affiliateDisclosure=text(body.affiliateDisclosure,300)||null;if(commercialType==='sponsored'&&!sponsorName)return NextResponse.json({error:'Sponsored ต้องระบุชื่อ Sponsor'},{status:400});if(commercialType==='affiliate'&&!affiliateDisclosure)return NextResponse.json({error:'Affiliate ต้องมี Disclosure'},{status:400});const reading=body.readingMinutes?Number(body.readingMinutes):null;if(reading!==null&&(!Number.isInteger(reading)||reading<1||reading>180))return NextResponse.json({error:'เวลาอ่านไม่ถูกต้อง'},{status:400});const{data:existing}=await supabase.from('articles').select('published_at').eq('id',id).maybeSingle();if(!existing)return NextResponse.json({error:'ไม่พบบทความ'},{status:404});const publishedAt=publicationStatus==='published'?(existing.published_at??new Date().toISOString()):null;const{error}=await supabase.from('articles').update({title,slug,excerpt:text(body.excerpt,500)||null,body_markdown:bodyMarkdown,category,destination_id:text(body.destinationId,80)||null,reading_minutes:reading,is_featured:body.featured==='on',commercial_type:commercialType,sponsor_name:sponsorName,affiliate_disclosure:affiliateDisclosure,seo_title:text(body.seoTitle,70)||null,seo_description:text(body.seoDescription,180)||null,publication_status:publicationStatus,published_at:publishedAt,updated_at:new Date().toISOString()}).eq('id',id);if(error)return NextResponse.json({error:error.message},{status:500});const relationError=await syncRelations(supabase,id,'article_places','place_id',ids(body.placeIds))||await syncRelations(supabase,id,'article_events','event_id',ids(body.eventIds));if(relationError)return NextResponse.json({error:relationError.message},{status:500});return NextResponse.json({success:true});}
