-- Phase 9 authenticated Business/Place CRUD policies.
begin;
create or replace function public.is_business_editor(target_business_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from business_members m where m.business_id=target_business_id and m.user_id=auth.uid() and m.role in('owner','admin','editor'))$$;
revoke all on function public.is_business_editor(uuid) from public;grant execute on function public.is_business_editor(uuid) to authenticated;
drop policy if exists "Members update businesses" on businesses;create policy "Members update businesses" on businesses for update to authenticated using(is_business_editor(id)) with check(is_business_editor(id));
drop policy if exists "Members manage places" on places;create policy "Members manage places" on places for all to authenticated using(is_business_editor(business_id)) with check(is_business_editor(business_id));
drop policy if exists "Members manage place images" on place_images;create policy "Members manage place images" on place_images for all to authenticated using(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id))) with check(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id)));
drop policy if exists "Members manage place hours" on place_hours;create policy "Members manage place hours" on place_hours for all to authenticated using(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id))) with check(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id)));
drop policy if exists "Members manage special hours" on place_special_hours;create policy "Members manage special hours" on place_special_hours for all to authenticated using(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id))) with check(exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id)));
drop policy if exists "Members manage prices" on price_items;create policy "Members manage prices" on price_items for all to authenticated using((place_id is not null and exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id)))or(event_id is not null and exists(select 1 from events e where e.id=event_id and is_business_editor(e.business_id)))) with check((place_id is not null and exists(select 1 from places p where p.id=place_id and is_business_editor(p.business_id)))or(event_id is not null and exists(select 1 from events e where e.id=event_id and is_business_editor(e.business_id))));
drop policy if exists "Members manage events" on events;create policy "Members manage events" on events for all to authenticated using(is_business_editor(business_id)) with check(is_business_editor(business_id));
drop policy if exists "Members manage event schedules" on event_schedules;create policy "Members manage event schedules" on event_schedules for all to authenticated using(exists(select 1 from events e where e.id=event_id and is_business_editor(e.business_id))) with check(exists(select 1 from events e where e.id=event_id and is_business_editor(e.business_id)));
commit;
