-- Phase 10: Admin roles and atomic Place moderation.
begin;
create table if not exists public.admin_users(user_id uuid primary key,role text not null default 'curator' check(role in('owner','admin','curator')),created_at timestamptz not null default now());
alter table public.admin_users enable row level security;
drop policy if exists "Admins read own role" on public.admin_users;create policy "Admins read own role" on public.admin_users for select to authenticated using(user_id=auth.uid());
insert into public.admin_users(user_id,role) select user_id,'owner' from public.hosts where user_id is not null order by created_at limit 1 on conflict(user_id) do nothing;
create or replace function public.is_geppao_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from admin_users a where a.user_id=auth.uid())$$;
revoke all on function public.is_geppao_admin() from public;grant execute on function public.is_geppao_admin() to authenticated;
alter table public.places add column if not exists moderation_note text,add column if not exists moderated_by uuid,add column if not exists moderated_at timestamptz;
create table if not exists public.place_moderation_log(id uuid primary key default gen_random_uuid(),place_id uuid not null references public.places(id) on delete cascade,decision text not null check(decision in('approve','reject','archive','return_to_draft')),note text,moderated_by uuid not null,created_at timestamptz not null default now());
alter table public.place_moderation_log enable row level security;
drop policy if exists "Admins read all places" on public.places;create policy "Admins read all places" on public.places for select to authenticated using(is_geppao_admin());
drop policy if exists "Admins read moderation log" on public.place_moderation_log;create policy "Admins read moderation log" on public.place_moderation_log for select to authenticated using(is_geppao_admin());
create or replace function public.moderate_place(target_place_id uuid,decision text,note text default null) returns public.places language plpgsql security definer set search_path=public as $$declare result public.places;begin if not is_geppao_admin() then raise exception 'Admin access required';end if;if decision='approve' then update places set publication_status='published',verification_status='verified',last_verified_at=now(),moderation_note=note,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=target_place_id returning * into result;elsif decision='reject' then update places set publication_status='rejected',verification_status='rejected',moderation_note=note,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=target_place_id returning * into result;elsif decision='archive' then update places set publication_status='archived',moderation_note=note,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=target_place_id returning * into result;elsif decision='return_to_draft' then update places set publication_status='draft',verification_status='unverified',moderation_note=note,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=target_place_id returning * into result;else raise exception 'Invalid moderation decision';end if;if result.id is null then raise exception 'Place not found';end if;insert into place_moderation_log(place_id,decision,note,moderated_by) values(target_place_id,decision,note,auth.uid());return result;end$$;
revoke all on function public.moderate_place(uuid,text,text) from public;grant execute on function public.moderate_place(uuid,text,text) to authenticated;
commit;
