-- Phase 11: queryable hours/pricing fields and type-detail permissions.
begin;
alter table public.place_hours add column if not exists valid_from date,add column if not exists valid_until date;
alter table public.place_special_hours add column if not exists crosses_midnight boolean not null default false;
alter table public.price_items add column if not exists audience text check(audience is null or audience in('all','adult','child','senior')),add column if not exists min_quantity integer check(min_quantity is null or min_quantity>0),add column if not exists valid_from timestamptz,add column if not exists valid_until timestamptz;
alter table public.events add column if not exists capacity integer check(capacity is null or capacity>0),add column if not exists reservation_required boolean not null default false,add column if not exists last_verified_at timestamptz,add column if not exists moderation_note text,add column if not exists moderated_by uuid,add column if not exists moderated_at timestamptz;
create unique index if not exists place_hours_unique_slot on public.place_hours(place_id,day_of_week,open_time) where not is_closed;
create unique index if not exists place_special_hours_unique_slot on public.place_special_hours(place_id,service_date,open_time) where not is_closed;
create index if not exists prices_validity_idx on public.price_items(place_id,valid_from,valid_until);
create index if not exists events_destination_status_idx on public.events(destination_id,publication_status);

do $$ declare t text; begin foreach t in array array['accommodation_details','dining_details','attraction_details','activity_details'] loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists "Public read published details" on public.%I',t);execute format('create policy "Public read published details" on public.%I for select using(exists(select 1 from public.places p where p.id=place_id and p.publication_status=''published''))',t);execute format('drop policy if exists "Members manage details" on public.%I',t);execute format('create policy "Members manage details" on public.%I for all to authenticated using(exists(select 1 from public.places p where p.id=place_id and public.is_business_editor(p.business_id))) with check(exists(select 1 from public.places p where p.id=place_id and public.is_business_editor(p.business_id)))',t);end loop;end$$;
create or replace function public.replace_place_hours(target_place_id uuid,items jsonb) returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from places p where p.id=target_place_id and is_business_editor(p.business_id)) then raise exception 'Business editor access required';end if;if jsonb_typeof(items)<>'array' then raise exception 'Hours must be an array';end if;delete from place_hours where place_id=target_place_id;insert into place_hours(place_id,day_of_week,open_time,close_time,is_closed,crosses_midnight,valid_from,valid_until) select target_place_id,(x->>'dayOfWeek')::smallint,nullif(x->>'openTime','')::time,nullif(x->>'closeTime','')::time,coalesce((x->>'isClosed')::boolean,false),coalesce((x->>'crossesMidnight')::boolean,false),nullif(x->>'validFrom','')::date,nullif(x->>'validUntil','')::date from jsonb_array_elements(items)x;end$$;
create or replace function public.replace_place_prices(target_place_id uuid,items jsonb) returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from places p where p.id=target_place_id and is_business_editor(p.business_id)) then raise exception 'Business editor access required';end if;if jsonb_typeof(items)<>'array' then raise exception 'Prices must be an array';end if;delete from price_items where place_id=target_place_id;insert into price_items(place_id,label,amount_min,amount_max,currency,price_unit,is_estimate,audience,min_quantity,valid_from,valid_until) select target_place_id,x->>'label',coalesce((x->>'amountMin')::numeric,0),nullif(x->>'amountMax','')::numeric,coalesce(nullif(x->>'currency',''),'THB'),x->>'unit',coalesce((x->>'isEstimate')::boolean,false),nullif(x->>'audience',''),nullif(x->>'minQuantity','')::integer,nullif(x->>'validFrom','')::timestamptz,nullif(x->>'validUntil','')::timestamptz from jsonb_array_elements(items)x;end$$;
revoke all on function public.replace_place_hours(uuid,jsonb) from public;grant execute on function public.replace_place_hours(uuid,jsonb) to authenticated;
revoke all on function public.replace_place_prices(uuid,jsonb) from public;grant execute on function public.replace_place_prices(uuid,jsonb) to authenticated;
commit;
