-- Phase 11: complete Place profile fields and dedicated Place image storage.
begin;
alter table public.places add column if not exists phone text,add column if not exists line_id text,add column if not exists email text,add column if not exists website_url text,add column if not exists indoor_outdoor text check(indoor_outdoor is null or indoor_outdoor in('indoor','outdoor','both')),add column if not exists advance_booking_hours integer check(advance_booking_hours is null or advance_booking_hours>=0);
alter table public.accommodation_details add column if not exists room_count integer check(room_count is null or room_count>=0);
alter table public.dining_details add column if not exists dietary_options text[] not null default '{}',add column if not exists alcohol_available boolean;
alter table public.activity_details add column if not exists instructor_required boolean not null default false;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('place-images','place-images',true,8388608,array['image/jpeg','image/png','image/webp']::text[]) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Public read place image objects" on storage.objects;create policy "Public read place image objects" on storage.objects for select using(bucket_id='place-images');
drop policy if exists "Business editors upload place images" on storage.objects;create policy "Business editors upload place images" on storage.objects for insert to authenticated with check(bucket_id='place-images' and exists(select 1 from public.places p where p.id::text=(storage.foldername(name))[2] and p.business_id::text=(storage.foldername(name))[1] and public.is_business_editor(p.business_id)));
drop policy if exists "Business editors update place images" on storage.objects;create policy "Business editors update place images" on storage.objects for update to authenticated using(bucket_id='place-images' and exists(select 1 from public.places p where p.id::text=(storage.foldername(name))[2] and p.business_id::text=(storage.foldername(name))[1] and public.is_business_editor(p.business_id))) with check(bucket_id='place-images' and exists(select 1 from public.places p where p.id::text=(storage.foldername(name))[2] and p.business_id::text=(storage.foldername(name))[1] and public.is_business_editor(p.business_id)));
drop policy if exists "Business editors delete place images" on storage.objects;create policy "Business editors delete place images" on storage.objects for delete to authenticated using(bucket_id='place-images' and exists(select 1 from public.places p where p.id::text=(storage.foldername(name))[2] and p.business_id::text=(storage.foldername(name))[1] and public.is_business_editor(p.business_id)));
commit;
