-- Phase 14: durable Trip workspace. Legacy trip_sessions remains untouched.
begin;
create table if not exists public.trips(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null,destination_id uuid references public.destinations(id),title text not null,start_date date,end_date date,travelers integer not null default 1 check(travelers>0),budget_total numeric check(budget_total is null or budget_total>=0),currency text not null default 'THB',preferences jsonb not null default '{}',status text not null default 'draft' check(status in('draft','planned','active','completed','archived')),share_token uuid unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or start_date is null or end_date>=start_date));
create table if not exists public.trip_members(trip_id uuid not null references public.trips(id) on delete cascade,user_id uuid not null,role text not null default 'viewer' check(role in('editor','viewer')),created_at timestamptz not null default now(),primary key(trip_id,user_id));
create table if not exists public.trip_days(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,day_number integer not null check(day_number>0),service_date date,title text,notes text,unique(trip_id,day_number));
create table if not exists public.trip_items(id uuid primary key default gen_random_uuid(),trip_day_id uuid not null references public.trip_days(id) on delete cascade,place_id uuid references public.places(id),event_id uuid references public.events(id),position integer not null default 0,starts_at timestamptz,ends_at timestamptz,estimated_cost numeric check(estimated_cost is null or estimated_cost>=0),currency text not null default 'THB',is_locked boolean not null default false,recommendation_reason text,notes text,created_at timestamptz not null default now(),check((place_id is not null)::integer+(event_id is not null)::integer=1),check(ends_at is null or starts_at is null or ends_at>starts_at));
create index if not exists trips_owner_idx on public.trips(owner_user_id,updated_at desc);create index if not exists trip_days_trip_idx on public.trip_days(trip_id,day_number);create index if not exists trip_items_day_idx on public.trip_items(trip_day_id,position);
create or replace function public.can_read_trip(target_trip_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from trips t where t.id=target_trip_id and t.owner_user_id=auth.uid()) or exists(select 1 from trip_members m where m.trip_id=target_trip_id and m.user_id=auth.uid())$$;
create or replace function public.can_edit_trip(target_trip_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from trips t where t.id=target_trip_id and t.owner_user_id=auth.uid()) or exists(select 1 from trip_members m where m.trip_id=target_trip_id and m.user_id=auth.uid() and m.role='editor')$$;
revoke all on function public.can_read_trip(uuid),public.can_edit_trip(uuid) from public;grant execute on function public.can_read_trip(uuid),public.can_edit_trip(uuid) to authenticated;
alter table public.trips enable row level security;alter table public.trip_members enable row level security;alter table public.trip_days enable row level security;alter table public.trip_items enable row level security;
create policy "Owners create trips" on public.trips for insert to authenticated with check(owner_user_id=auth.uid());create policy "Members read trips" on public.trips for select to authenticated using(public.can_read_trip(id));create policy "Editors update trips" on public.trips for update to authenticated using(public.can_edit_trip(id)) with check(public.can_edit_trip(id));create policy "Owners delete trips" on public.trips for delete to authenticated using(owner_user_id=auth.uid());
create policy "Members read trip members" on public.trip_members for select to authenticated using(public.can_read_trip(trip_id));create policy "Owners manage trip members" on public.trip_members for all to authenticated using(exists(select 1 from trips t where t.id=trip_id and t.owner_user_id=auth.uid())) with check(exists(select 1 from trips t where t.id=trip_id and t.owner_user_id=auth.uid()));
create policy "Members read trip days" on public.trip_days for select to authenticated using(public.can_read_trip(trip_id));create policy "Editors manage trip days" on public.trip_days for all to authenticated using(public.can_edit_trip(trip_id)) with check(public.can_edit_trip(trip_id));
create policy "Members read trip items" on public.trip_items for select to authenticated using(exists(select 1 from trip_days d where d.id=trip_day_id and public.can_read_trip(d.trip_id)));create policy "Editors manage trip items" on public.trip_items for all to authenticated using(exists(select 1 from trip_days d where d.id=trip_day_id and public.can_edit_trip(d.trip_id))) with check(exists(select 1 from trip_days d where d.id=trip_day_id and public.can_edit_trip(d.trip_id)));
create or replace function public.get_shared_trip(target_share_token uuid) returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('trip',to_jsonb(t)-'owner_user_id'-'share_token','days',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'dayNumber',d.day_number,'serviceDate',d.service_date,'title',d.title,'notes',d.notes,'items',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'position',i.position,'startsAt',i.starts_at,'endsAt',i.ends_at,'estimatedCost',i.estimated_cost,'currency',i.currency,'reason',i.recommendation_reason,'place',case when p.publication_status='published' then jsonb_build_object('id',p.id,'name',p.name,'slug',p.slug,'type',p.place_type) end,'event',case when e.publication_status='published' then jsonb_build_object('id',e.id,'name',e.name,'slug',e.slug) end) order by i.position) from trip_items i left join places p on p.id=i.place_id left join events e on e.id=i.event_id where i.trip_day_id=d.id),'[]'::jsonb)) order by d.day_number) from trip_days d where d.trip_id=t.id),'[]'::jsonb)) from trips t where t.share_token=target_share_token$$;
revoke all on function public.get_shared_trip(uuid) from public;grant execute on function public.get_shared_trip(uuid) to anon,authenticated;
commit;
